### ISSUE TITLE
Hello, I have this error after local deployment. Can help

### ISSUE THREAD

**Issue by dgo2dance** [monoid-privacy/monoid#8]
Hello, I have this error after local deployment. Can help
![monoid](https://user-images.githubusercontent.com/1674662/206849154-7d732043-beff-4fcb-b9ac-ca96fc4153ca.jpeg)

**Comment by vigneshv59** [comment]
Hi @dgodance, sorry for the late reply -- are you trying to connect a MySQL database that is running on your local machine? If so, you'll want to use `host.docker.internal` as the hostname instead of `127.0.0.1` (since our connectors run in docker, this is the way to connect to the host). Happy to debug in more detail in our [Slack](https://monoidworkspace.slack.com), if that would be helpful!

**Comment by jagathv** [comment]
Unable to reproduce this issue. If the issue persists/others are experiencing this issue, please revive.
